### ISSUE TITLE
Add Redux Hooks Support

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#118]
- [ ] - Create Redux State Types for all reducers

**Comment by ZibanPirate** [comment]
@Souhaib-Benbouzid the state interface is already availabe, see:
[frontend/src/apps/main/types/index.ts](https://github.com/dzcode-io/dzcode.io/blob/e9d8e6d1c1e861e3dc3a140dac7c2a917a5792a1/frontend/src/apps/main/types/index.ts#L3)
