### ISSUE TITLE
Update Read Me 

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#148]
Update Read Me to reflect open source workflow with forking and pull requests

**Comment by NurElHuda** [comment]
The new changes should explain about the pre-commit tasks needed for future commits. Like running Prettier.

At first, I didn't know about them, and took me some time and some search to figure them out and do the tasks. 

I think the documentation should consider devs who didn't work with node.js before.

**Comment by ZibanPirate** [comment]
@NurElHuda readme updated in #192
