### ISSUE TITLE
fix contact page card overlap with the navbar

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#153]
**Describe the bug**
fix contact page card overlap with the navbar

**To Reproduce**
1. Go to https://www.dzcode.io/Contact-Us/
2. See card overlap

**Expected behavior**
a clean separation between the navbar and contact card component

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**
-Browser: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by sidou01** [comment]
Adding `position: relative` to the contact class should fix  this issue.
