### ISSUE TITLE
Fix Links color contrast on dark mode in articles

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#160]
**Describe the bug**
Not enough contrast on dark mode between the blue links color and the background

**To Reproduce**
1. Go to https://www.dzcode.io/Articles/Welcome_to_dzCode
2. Scroll down to find a link
3. See error

**Expected behavior**
a better contrast to increase readability

**Comment by AM-77** [comment]
Hi there, I'm gonna try to fix this one, since it's not assigned to anyone, if that's okey.
