### ISSUE TITLE
Links in dark mode are hard to read due it's dark blue color

### ISSUE THREAD

**Issue by AymenSekhri** [dzcode-io/dzcode.io#161]
**Describe the bug**
As the title says, Links in dark mode are hard to read due it's dark blue color (or it might be my poor eyes)

**To Reproduce**
1. Activate Dark mode
2. Go to any article that contains links, [for example](https://www.dzcode.io/Articles/Send_Emails_With_Django_and_Gmail_A_Btter_Way)  

**Expected behavior**
The color should have more contrast.

**Screenshots**
![16534646534](https://user-images.githubusercontent.com/16035332/92937108-d7935f80-f442-11ea-9b94-8151e882c96b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2004

**Comment by Souhaib-Benbouzid** [comment]
Well described thank you for reporting. 

the issue is duplicated see #160

**Comment by AymenSekhri** [comment]
I haven't noticed it when I wrote it lol
Good luck.
