### ISSUE TITLE
Navbar & General UI/UX changes

### ISSUE THREAD

**Issue by yzdbg** [dzcode-io/dzcode.io#163]
**UI Changes**
Following up on UX changes discussion on slack, Below is a mock-up of changes that would, In my humble opinion, simplify the UI and Improve general UX.
![-](https://i.imgur.com/hN0Nq4w.png)
Illustration is open-source, alternatives can be found [Here](https://undraw.co/illustrations) scrum board made sense here tho haha.

**Comment by ZibanPirate** [comment]
This is way cleaner and easier for the user
thanks for the suggestions 

@yzdbg We definitely going to implement this
