### ISSUE TITLE
Update Home Page Content 

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#177]
**Remove duplicate links** 
- [x] contact
- [x] faq

**Remove Search icon until further notice**

**add Top Community Projects** 

- [x] leblad project

**Update How To Contribute to dzCode.io**

**add Top Community Articles**

- [x] [How To Add Your Own Article](https://www.dzcode.io/Articles/Add_Your_Own_Article)
- [x] [Send emails with Django and Gmail, a better way](https://www.dzcode.io/Articles/Send_Emails_With_Django_and_Gmail_A_Btter_Way)

**Comment by yzdbg** [comment]
Hi, for the search icon and redundant links i'm already on that ! :)

**Comment by Souhaib-Benbouzid** [comment]
implemented #214
