### ISSUE TITLE
Update Learn Page Content

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#178]
- [ ] Getting Started
- [ ] Git Basics
- [ ] Git and Github
- [ ] Basic Git Commands
- [ ] Managing Conflict
- [ ] Collaboration
- [ ] Advanced Git
- [ ] Git Reflog
- [ ] Git Clean
- [ ] Git Rebase

**Comment by ZibanPirate** [comment]
closing as done in v1 release
