### ISSUE TITLE
 Add  Service Workers and PWA for  Offline support  

### ISSUE THREAD

**Issue by abderrahmaneMustapha** [dzcode-io/dzcode.io#184]
When there is no internet connection the user can not access the  articles or the learn section

we can use a service worker and progressive web apps to add offline support and make your web app installable like native apps

**Comment by ZibanPirate** [comment]
yes, a very welcomed feature, i'm planning to add it once the website is stable, otherwise the caching will cause serious problem later, @abderrahmaneMustapha you can try implementing it, will test it on staging first.

**Comment by ZibanPirate** [comment]
we decided to keep the website as minimal as possible, will close this for now, and will bring it back when there is a real need for it, thank you for reporting it @abderrahmaneMustapha !
