### ISSUE TITLE
Serve images with the article file.

### ISSUE THREAD

**Issue by NurElHuda** [dzcode-io/dzcode.io#186]
If we want to add an image to an article, we have to host it in a third party place then reference it from there. 

It would be benefcial if the node.js server serve the images linked to the articel as well, and does not require the use  of third party to do so.

**Comment by Souhaib-Benbouzid** [comment]
Currently we don't have an effective way to handle images. adding them to the repository will make it grow out of hands as there is no limit to the amount of articles, projects, and images in each article. hosting them on a dedicated service is much more effective. maybe we will consider this in future releases. thank you for the suggestion.

**Comment by ZibanPirate** [comment]
closing this because we no longer host our own articles, will re-open it once we bring back articles
