### ISSUE TITLE
can't choose Article while i am using my phone

### ISSUE THREAD

**Issue by AhmedAbdelhak1** [dzcode-io/dzcode.io#190]
**Describe the bug**
while using the phone to check dzcode.io all things are fine but when i select the article page nothing show up which make it impossible to choose the article that i want to read. 

**To Reproduce**
1. Go to 'dzcode.io '
2. Click on 'toggle device toolbar'
3. Click on 'Articles'

**Expected behavior**
It should be a list of Articles to pick one to read to make it easy fo the user when he use the phone.

**Desktop (please complete the following information):**
 - OS: [windows]
 - Version [10]

**Additional context**
Google Chrome.

**Comment by ZibanPirate** [comment]
there is a button on the bottom-left corner which will display the list of articles
![119990272_742198709845516_2801098479313956706_n](https://user-images.githubusercontent.com/20110076/93734998-7743b100-fbec-11ea-950c-fd4c456405ee.jpg)

but yes, this issue still valid, we need to add a proper blank page for `/Articles`

**Comment by ZibanPirate** [comment]
closing as it's fixed in the v1 release
