### ISSUE TITLE
Design for Learn Scene

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#20]
As a visitor, I should see contribution guide articles, and browse them, read, write, modify, react & comment on any article.

scenarios:

- [x] browse article from the sidebar
- [x] Read article
- [x] Modify article
- [x] React to articles
- [x] Comment on an articles

**Comment by Souhaib-Benbouzid** [comment]
I've completed the UI. 

1. [Add Post ](https://www.figma.com/proto/wh7j8aRwCIn207HlzKkTQM/Dzcode.io?node-id=142%3A223&scaling=scale-down-width)
2. [Read Post] (https://www.figma.com/proto/wh7j8aRwCIn207HlzKkTQM/Dzcode.io?node-id=57%3A112&scaling=scale-down-width) and you can comment and edit the post directly if you are logged in.
3. [browse articles] (https://www.figma.com/proto/wh7j8aRwCIn207HlzKkTQM/Dzcode.io?node-id=142%3A0&scaling=scale-down-width)

**Comment by Souhaib-Benbouzid** [comment]
I reworked the design so the user can write and add the post in markdown now.

. Note that the Learn and Blog scene has the same UI. the difference between is you need the 

1. [Add Post ](https://www.figma.com/proto/wh7j8aRwCIn207HlzKkTQM/Dzcode.io?node-id=142%3A223&scaling=scale-down-width)
2. [Read Post](https://www.figma.com/proto/wh7j8aRwCIn207HlzKkTQM/Dzcode.io?node-id=33%3A104&scaling=scale-down-width) and you can comment and edit the post directly if you are logged in.
