### ISSUE TITLE
fix: No image Articles and Projects UI

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#210]
Articles without images appear broken

![Capture](https://user-images.githubusercontent.com/54677068/95626736-c30eab00-0a72-11eb-9b76-5d07a9692756.PNG)

**Comment by ZibanPirate** [comment]
@abderrahmaneMustapha it's the image link issue we talked about last time

**Comment by Souhaib-Benbouzid** [comment]
@abderrahmaneMustapha can you please provide an image for the articles.
