### ISSUE TITLE
WYSIWYG editor for articles, documentation & projects

### ISSUE THREAD

**Issue by souhaib-benbouzid** [dzcode-io/dzcode.io#218]
The user should be able to Add/Edit any Article, Documentation or Project, from within dzcode.io website, using a UI component that preview the changes and automate the process of creating a PR by providing Github account information

**Comment by khalilmansouri** [comment]
I suggest using [SunEditor](suneditor.com)  or [Draftjs](https://draftjs.org), unless you guys thinking of building it from scratch

**Comment by ZibanPirate** [comment]
i like Draftjs, but will have to explore each option, thank you for the suggestions @khalilmansouri !

**Comment by ZibanPirate** [comment]
we can also consider beta.dawin.io since it's built by dz dev

**Comment by khalilmansouri** [comment]
I'll check it out, please share the repo

**Comment by omdxp** [comment]
I suggest [lexical](https://lexical.dev)

**Comment by ZibanPirate** [comment]
closing this because we no longer host our own articles, will re-open it once we bring back articles
