### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by khalilmansouri** [dzcode-io/dzcode.io#237]
Adding locals to the platform, would a great idea in order to address deferent audience with deferent languages,  ex : French / Arabic

**Comment by ZibanPirate** [comment]
thank you @khalilmansouri for your suggestions, this feature will be implemented in the near future, you can keep tracking it on #24 , and let us know if you think you can help on this

**Comment by ZibanPirate** [comment]
closing as duplicate of #24
