### ISSUE TITLE
Articles titles case inconsistency

### ISSUE THREAD

**Issue by Noisy96** [dzcode-io/dzcode.io#241]
### Description
There's a minor but annoying inconsistency regarding the letter cases used for the articles titles, more precisely some use:

__Sentence case:__ "Use conventional commits to contribute to dzcode."
while others use
__Title case:__ "How to Add your Article to dzCode."

I would personally recommend "Title case" as a proper and even aesthetically better option.
in case you agree, I already took the liberty to make the changes, let me know if you want that pull request.

**Comment by ZibanPirate** [comment]
thank you for the remark @Noisy96 , and also thank you for the PR, this is much needed!

i'm also thinking of adding a linting check for the title, to enforce one convention.

**Comment by Noisy96** [comment]
That would be good, however it may get tricky for none-native to apply to __Title case__ rules flawlessly, as it's not super straight-forward,

#### I'd suggest:
* you recommend using a converting tool such as [convertcase](convertcase.net) __and__ treating every title that doesn't respect the case as typo that needs correction.

enforcing a conversion with a function or blocking the merging for title case might be an overkill, may also create further problems.

Do you want a PR that corrects the current articles?

**Comment by ZibanPirate** [comment]
i see, for now, i will note down the suggestion "setup linting with warning level for title cases in Data", and think about a good automated solution, also, if you think you can help on this, please feel free to mess with the code 😀.

And yes, we will never say no to new PRs, so please go ahead and submit as much fixes as you can, that would be appreciated, we will create a new release after the second PR, please note that, better limit the changes to one stack folder per PR, for eg, put changes in the `data` folder in one PR, and changes in `frontend` folder in another PR, this will help in managing conflicts later, as we are currently working on a breaking change that will be published soon, see [main](https://github.com/dzcode-io/dzcode.io/tree/main) branch

**Comment by ZibanPirate** [comment]
hey @Noisy96 please be informed that now the default branch is `main` with breaking changes, also a new version is deployed to production, please check again https://dzcode.io

**Comment by ZibanPirate** [comment]
seems like #240 resolved this issue, closing ...

feel free to reopen if the issue still there
