### ISSUE TITLE
using dependency injection for API server, for cleaner code

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#277]
**Is your feature request related to a problem? Please describe.**
The code inside the `api` folder is a bit messy...

**Describe the solution you'd like**
One way to improve it, is to use one of the strategies of IoC, which is dependency injection.
since this is a Nodejs server, we can use an npm package to handle dependency injection, the library i recommend is: [typedi](https://github.com/typestack/typedi.git) 

**Describe alternatives you've considered**
There are other way to improve it too, like using a framework on top of express (eg: Nest.js)

**Additional context**
N/a

**Feature Branch** : [`feat/cleaner-api`](https://github.com/dzcode-io/dzcode.io/tree/feat/cleaner-api)
**Feature PR** :  #283

**Comment by well-balanced** [comment]
I'd like to tackle with this. is there a dead line for this issue?

**Comment by ZibanPirate** [comment]
Please go on, if you know what to do, I will support you on it

**Comment by well-balanced** [comment]
I created a PR related with `loader` as a first step. please give me a feedback 😊

**Comment by well-balanced** [comment]
I've looked over the api codes. but I couldn't find dependencies for each service functions. could you give me an example?

**Comment by ZibanPirate** [comment]
i will create a feature branch, with a sample code containing DI, we will start from there

**Comment by ZibanPirate** [comment]
closing as done in #283
