### ISSUE TITLE
API root page does not exist.

### ISSUE THREAD

**Issue by well-balanced** [dzcode-io/dzcode.io#280]
**Is your feature request related to a problem? Please describe.**
when I first run api server, I've faced the `Not Found` message on the browser. I think there is a probability that someone who want to contribute will be confused.

**Describe the solution you'd like**
- Create a root controller

**Additional context**
if you guys don't mind, can I take over this issue?

**Comment by ZibanPirate** [comment]
Thank you @well-balanced it make sense, sure please go ahead

**Comment by well-balanced** [comment]
thanks :)

**Comment by well-balanced** [comment]
I'll close this issue. It has already merged
