### ISSUE TITLE
Migrating old endpoints to v2 API

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#286]
**Description**

after merging #283 , the old code is still working (old controllers/services), we need to migrate them to the new code and expose the APIs under `/v2`, bellow are the tasks needed to accomplish this:

**Check List**

1. [x] Call `/v2/Contributors` endpoint from frontend, instead of old endpoint `/Contributors`, and remove the last.
    -  The API code for Contributors Controller get method is [here](https://github.com/dzcode-io/dzcode.io/blob/f54895bba3a432754d9174a4259e2c7999b4e61a/api/src/contributor/controller.ts#L19)
    - The Frontend code for calling the old endpoint is [here](https://github.com/dzcode-io/dzcode.io/blob/f54895bba3a432754d9174a4259e2c7999b4e61a/web/src/apps/main/redux/actions/articles-page/index.ts#L63) and [here](https://github.com/dzcode-io/dzcode.io/blob/f54895bba3a432754d9174a4259e2c7999b4e61a/web/src/apps/main/redux/actions/documentation-page/index.ts#L63)
2. [x] Create `/v2/GithubUsers` endpoint and call it from frontend instead of `/github/users`, and remove the last.
   - You will create a new method inside Github service similar to [listContributors method](https://github.com/dzcode-io/dzcode.io/blob/f54895bba3a432754d9174a4259e2c7999b4e61a/api/src/github/service.ts#L8), but the logic will be that of the old [getUser method](https://github.com/dzcode-io/dzcode.io/blob/f54895bba3a432754d9174a4259e2c7999b4e61a/api/src/app/services/github/index.ts#L216)
   - You will create a new mod**u**le `api/src/github-user` and inside you create your controller `api/src/github-user/controller.ts` similar to [Contributors' controller](https://github.com/dzcode-io/dzcode.io/blob/f54895bba3a432754d9174a4259e2c7999b4e61a/api/src/contributor/controller.ts). where you call the newly created method of GithubService.
   - Then update the frontend to call the new endpoint instead of the old one [here](https://github.com/dzcode-io/dzcode.io/blob/f54895bba3a432754d9174a4259e2c7999b4e61a/web/src/apps/main/redux/actions/articles-page/index.ts#L101) and [here](https://github.com/dzcode-io/dzcode.io/blob/f54895bba3a432754d9174a4259e2c7999b4e61a/web/src/apps/main/redux/actions/documentation-page/index.ts#L100)

**Additional Comments**

please create new PR for each task.

**Comment by ZibanPirate** [comment]
@well-balanced this is much clearer task i believe, if you wanna take up any, feel free to do so, and ofc i'm here for any questions :)

**Comment by well-balanced** [comment]
@ZibanPirate thanks for your clean description I really appreciate it 🙏 I've just implemented tasks those are included in the checklist. check plz 😊

**Comment by ZibanPirate** [comment]
checking ...

**Comment by ZibanPirate** [comment]
closing as done in #290 and #289
