### ISSUE TITLE
Adding projects and articles directly from website

### ISSUE THREAD

**Issue by omdxp** [dzcode-io/dzcode.io#308]
When I clicked on the contribute button that takes to [www.dzcode.io/Contribute](https://www.dzcode.io/Contribute) I found that this page is not implemented yet and thus it rises an idea for me and that is what if there is a way to add projects and articles directly from the website without forking and adding to json files like we always do. 

Other than that, this website is one of the awesome ones and definitely I'm proud of it. 

![image](https://user-images.githubusercontent.com/48713070/119314037-26e58d00-bc6c-11eb-87b7-c35850cdef9f.png)

**Comment by ZibanPirate** [comment]
nice idea @Omar-Belghaouti thanks for the feedback! i'm thinking we can add this as part of #218

**Comment by ZibanPirate** [comment]
closing this because we no longer host our own articles, will re-open it once we bring back articles
