### ISSUE TITLE
Articles are empty and shown in menu, and Title not reflecting the current page

### ISSUE THREAD

**Issue by Fcmam5** [dzcode-io/dzcode.io#314]
As a random user (for real) I wanted to click on random articles, and un-luckily I landed on empty ones before I find the ones with actual content.

It might be that they were eyecatching (longer/more interesting titles or they were ranked before).

![image](https://user-images.githubusercontent.com/9090674/122471617-c40fb900-cfbf-11eb-9a0d-e29ae8e10d5d.png)

I think that it's better to have a small menu than to have a long one with empty content.

--- 

Also, another small bug: Page title doesn't change after leaving the page, so if I land on: https://www.dzcode.io/Learn/Git_Basics/What_The_Fork 

My tab title will be "What the Fork!" everywhere. 

Aaaand last: I suggest keeping the site name as a part of the tab title, so we should set:

`<title>Article title | dzCode i/o</title>`

**Comment by ZibanPirate** [comment]
for the title issue, https://github.com/nfl/react-helmet should solve it

**Comment by ZibanPirate** [comment]
reopening for the "Title" part of this issue

**Comment by ZibanPirate** [comment]
closing this because we no longer host our own articles, will re-open it once we bring back articles
