### ISSUE TITLE
Creating a documentation for contribution guide

### ISSUE THREAD

**Issue by abdeldjalilhachimi** [dzcode-io/dzcode.io#315]
1. Contributors can use documentation as a guide to contribute.
2.  Contributor can Understand the project's workflow via documentation. 
3.  Contributor can follow code guide based on what is written on documentation.
4.  Contributor can follow style guide based on what is written on documentation.

**Comment by ZibanPirate** [comment]
closing this because we no longer host our own documentation, will re-open it once we bring back documentation, for now the main Readme should be enough to get started
