### ISSUE TITLE
Error when using yarn with husky command

### ISSUE THREAD

**Issue by Omar-Belghaouti** [dzcode-io/dzcode.io#340]
**Error when using `yarn` with `husky` command**
Hi, when I try to execute the `yarn` command to install the dependencies, the following command returns an error with code 1:
```sh
$ (husky install && husky set .husky/pre-commit "yarn workspaces run lint-staged
yarn --cwd mobile lint-staged") || exit 0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
The same happens when I try `yarn dev:web` or `yarn deb:mobile`.

**To Reproduce**

1. Go to the project's root.
2. Execute the `yarn` command.
3. It installs all the dependencies needed for all projects (api, web, mobile).
4. It shows the error above.
5. The same happens when using `yarn dev:web` or `yarn dev:mobile`.

**Expected behavior**
Command execute with status code of 0 "success".

**Environment:**

- OS: Windows 11 Home build 22000.100

**Comment by ZibanPirate** [comment]
hey @Omar-Belghaouti sorry this happened, for now you can just remove the `postinstall` script from the root's package.json, i will debug this later today and see what's going on there.

**Comment by Omar-Belghaouti** [comment]
@ZibanPirate it's fine, thanks
