### ISSUE TITLE
Clean up code under ./mobile folder

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#362]
**Description**

As discussed with @Omar-Belghaouti after #361 , we can now clean up code under `./mobile`

**Check List**

1. [x] remove `JSX.Element` redundant annotation on all FC components.
2. [x] Remove comments where the code is self explanatory.
3. [x] Use named exports instead of default exports whenever possible
4. [x] Use fetch instead of Axios, and create a wrapper around it that takes care of setting up endpoints type checking.
5. [x] Removed dead code from the latest Redux integration.
6. [x] Change `UI` to `Screen`.
7. [x] Make `Drawer.Screen.name` lowercase
8. [x] sort imports
9. [x] add `./src/entry` folder, that contains entry point (`index.ts`), and other logic to bootstrap the app.
10. [x] import `./.common` things directly (looking at you `./src/utils/functions`)
11. [x] remove files that are not imported yet (eg: `./src/components/app-bar/style.ts`)
12. [x] inside `./src/redux/reducers`, we should rename files ending with `-page` to `-screen` as we are in `./mobile` not `./web` anymore haha
14. [x] redo task#7 for `./mobile/src/screens/articles/navigation.tsx`
15. [x] refactor `./mobile/src/screens/contribute/card-item/index.tsx` to properly use TS types
16. [x] use named exports in `./src/screens`
13. [ ] create a wrapper around `fetch` with typed responses and endpoints

**Additional Comments**

Feel free to disagree/discuss any points, or add missing points

**Comment by ZibanPirate** [comment]
my suggested improvements over the current folder structure is the following:

```
.
├── .common   <-- auto-generated
├── assets    <-- with the following format assets/[extension]/[file name].[extension]
│   │── ttf
│   │    └── spacemono-regular.ttf
│   └── png
│        └── branching.png
├── components    <-- contains shared components
│   ├── app-bar
│   │    │── style.ts
│   │    └── index.tsx
│   └── loading
│        │── style.ts
│        └── index.tsx
├── screens    <-- contains screens, sub-screens and non-shared components
│   ├── landing
│   │    │── style.ts
│   │    └── index.tsx
│   └── contribute
│        │── style.ts
│        |── index.tsx    <-- the screen itself, which display both components: contributions and filters.
│        |── contributions    <-- component that is only used inside contribute screen
│        │    |── style.ts
│        │    └── index.tsx
│        └── filters          <-- component that is only used inside contribute screen
│             |── style.ts
│             └── index.tsx
├── config    <-- contains global config such fullStackConfig
├── redux     <-- The whole state of the app (data layer)
│   ├── index.ts
│   │── actions <-- functions that modify the state (called by UI)
│   │    |── contribute-page
│   │    │    └── index.ts
│   │    └── general
│   │         └── index.ts
│   └── reducers <-- functions that form the state
│        |── index.ts
│        |── contribute-page
│        │    └── index.ts
│        └── general
│             └── index.ts
└── utils     <-- All the util functionalities that are only used inside the mobile code.
```

- instead of writing `./component.tsx`, we write `./component/index.tsx`, this way the import still works the same way, and as a plus, we get to write different files inside `./component` such as `./component/style.ts` or `./component/sub-component/index.tsx`.
- things that we get from `./.common` we require them directly, abstracting them even more defeats the purpose.
- inside the view layer (`./components/**` and `./screens/**`), we get the data from the state using Redux selector hook `useSelector`. we never modify the state directly from the view layer, we instead call (dispatch) action creators (functions inside `./redux/actions/**`) which will handle modifying the state. We dispatch these actions using Redux dispatch hook `useDispatch`.
- inside the data layer (`./redux/**`), the actions creators are the only code that should modify the state, by using the first two params: `dispatch` to modify the state or dispatch more actions, `getState` calling it will get us the state, which we may need to check on our state.
- well, the previous two point is not 100% true, cuz, we can still call actions (not action creators) directly from the view layer, to do small modification to the state. such as updating an input value in onChange event, using the same Redux Dispatch hook.

**Comment by Omar-Belghaouti** [comment]
@ZibanPirate sounds a good structure to me ☄️ that I'll work on it in my next PR, it'll be more readable this way, however in the `redux` section we need a place where we define our action types (i.e `constants/index.ts`). Also it'll be better to work only with action creators whenever we change the state in the cache, even for small functionalities, that way the code can be more readable as well! 🐱‍🏍

**Comment by ZibanPirate** [comment]
reopening to finish the last tasks with #368
