### ISSUE TITLE
can't run "yarn dev" on frontend in Windows terminal

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#39]
**Describe the bug**

I can't start the development environment on a windows os. the bug is due to a failure to compile.

**To Reproduce**
on a windows os : 
1.  Go to ' dzcode.io\frontend''
2. run yarn dev '
4. See error ' Failed to compile. '

**Expected behavior**
start a development environment and compile successfully.

**Screenshots**
![2](https://user-images.githubusercontent.com/54677068/82712977-f80f9200-9c78-11ea-9592-94e54fb6b93a.JPG)

**Desktop:**
 - OS: windows 10
 - Version	10.0.10240 Build 10240
.

**Comment by ZibanPirate** [comment]
It should be fixed by [this commit](https://github.com/dzcode-io/dzcode.io/commit/7ea2a6c2a67dec8ee693d6cc040d86c0cb4851b8)

**Comment by Souhaib-Benbouzid** [comment]
I find out I had to build the full stack folder since the file config is referenced in the import. the files do compile successfully. however the server on http://0.0.0.0:8080/ gives me an error site can't be reached and on http://localhost:8080/ it fails to load the components.
