### ISSUE TITLE
Migration to `@dzcode.io/ui`: check list

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#406]
- [x] #488
- [x] #535
- [x] #533
- [x] #522
- [x] #531
- [x] #524
- [x] #526
- [x] #529
- [x] #537
- [x] #539

**Comment by ZibanPirate** [comment]
we should probably rename this to be something about `@dzcode.io/ui`, and link it to #433 , and maybe close #417

**Comment by ZibanPirate** [comment]
hey @Souhaib-Benbouzid let's follow the [atomic-design pattern](https://medium.com/@janelle.wg/atomic-design-pattern-how-to-structure-your-react-application-2bb4d9ca5f97)

**Comment by Souhaib-Benbouzid** [comment]
I agree
