### ISSUE TITLE
Migrate `Project` endpoint from `data` to `api`

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#407]
**Description**

Since we have an API server now, the static `data.dzcode.io` is not needed, as a first step to migrating it to API, we start with the `Project` endpoint.

**Check List**

1. [ ] Create `Project` controller and endpoint with OpenAPI specs
2. [ ] Create `Project` repository that get data from both `./data` folder & `Github` service
3. [ ] Update `./web` and `./mobile` code to use the new `./api` endpoint

**Additional Comments**

once all models are migrated to `./api`, we can decommission `data.dzcode.io` cc @CA1R7  ;)

**Comment by CA1R7** [comment]
Great @ZibanPirate finally 🔥🤩

**Comment by ZibanPirate** [comment]
finally starting to work on this one 😄, will close this as a duplicate of #549 and will track progress there instead
