### ISSUE TITLE
DX Improvement

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#480]
**Description**

Improve dev experience a bit, by updating our tooling and the packages we use

**Check List**

- [x] #431
- [x] #482 
- [x] #490
- [x] #486
- [x] #492

**Comment by Omar-Belghaouti** [comment]
@ZibanPirate I was think perhaps it's the time to use relative imports as well in the mobile codebase.

Old:
```ts
import { ErrorBoundary } from "../../../components/error-boundary";
```

New:
```ts
import { ErrorBoundary } from "components/error-boundary";
```

**Comment by ZibanPirate** [comment]
our first successful milestones are now closed yay 🎊

**Comment by omdxp** [comment]
Congrats to us! it's been so fun
