### ISSUE TITLE
migrate mobile common components to `@dzcode.io/ui-mobile`

### ISSUE THREAD

**Issue by omdxp** [dzcode-io/dzcode.io#494]
migrating mobile common components to `@dzcode.io/ui-mobile`

- [x] AppBar
- [x] DrawerContent
- [x] ErrorBoundary
- [x] Loading
- [x] TryAgain

**Comment by ZibanPirate** [comment]
What's the package name gonna be? `@dzcode.io/mobile`? `@dzcode.io/ui-mobile`? `@dzcode.io/mui`🙃? Or what?

**Comment by omdxp** [comment]
I thought it'll be `@dzcode.io/mobile` since it'll contain some other sub packages other than `ui`, maybe `hooks`, `utils` ?

**Comment by ZibanPirate** [comment]
That's an interesting approach, so the ui package will be in `./packages/mobile/ui/package.json`, then later we can add other packages that are consumed by mobile only in `./packages/mobile/[another mobile only package name]/package.json`

And we import them like:

`import { Button } from "@dzcode.io/mobile/ui/dist/button"`

I'm fine with that.


One important note, make sure to first setup the package with a single simple component and consume it in `./mobile`, in one PR. Once that is green, you can then continue adding the rest of component in follow PR/PRs
