### ISSUE TITLE
Migration to `@dzcode.io/ui-mobile`: check list

### ISSUE THREAD

**Issue by omdxp** [dzcode-io/dzcode.io#495]
**Description**
This milestone is dedicated to create a `@dzcode.io/ui-mobile` package that contains common components in the mobile codebase.

**Check List**
- [x] #496
- [x] #494 
- [x] #499
- [x] #502
- [x] #505
- [x] #508
- [x] #511
- [x] #517

**Comment by ZibanPirate** [comment]
I think we should also migrate other components, the ones from:
- `@react-native-community/masked-view`
- `@react-navigation/bottom-tabs`
- `@react-navigation/drawer`
- `react-native-markdown-display`
- `react-native-paper`
- essentially, any Visual componets has to be imported from `@dzcode.io/ui-mobile`

**Comment by omdxp** [comment]
So you want a wrapper for all these packages ?

**Comment by ZibanPirate** [comment]
ideally yes, a wrapper like I'm doing in [src/v2/divider](https://github.com/dzcode-io/dzcode.io/pull/489/files#diff-916ad97932f5a4c8e787d46d803d9cc257a4f028afa75e36ff411d38973d0a9c), with a consistent props interface, or, simply just an export from the package so we would import from our internal package even though it's literally just an export redirection.
