### ISSUE TITLE
publish `/packages` to npm registry

### ISSUE THREAD

**Issue by omdxp** [dzcode-io/dzcode.io#567]
**Is your feature request related to a problem? Please describe.**
Currently our packages are used locally in this repo. It'll be a good thing to share it to other devs to use it for their specific use cases.

**Describe the solution you'd like**
Publishing all shared packages as `@dzcode.io/ui`, `@dzcode.io/ui-mobile`, `@dzcode.io/tooling` and `@dzcode.io/utils` to npm would be a huge help for other devs.

We also need to discuss about the versioning for these packages.

**Comment by ZibanPirate** [comment]
i can't think of a specific piece of code that can be shared as a standalone package right now, is this issue still relevant? or do you think we should close it for now and re-open it when such cases exists in the future?

**Comment by omdxp** [comment]
This was opened when there was relevant UI packages (mobile & web) since this project is and still a platform app with its own design system, would be better if we still have that idea of sharing used components and design system

**Comment by ZibanPirate** [comment]
since we're using daisyui and trying to keep things minimal, I don't see us having unique features that can be shared as packages, will close this for now, and maybe open a Github discussion instead for those types of issues
