### ISSUE TITLE
Provide Design for landing page

### ISSUE THREAD

**Issue by ZibanPirate** [dzcode-io/dzcode.io#6]
Simple initial design cc @SofianeHamlaoui please cite the sections of the landing page with brief description

**Comment by SofianeHamlaoui** [comment]
### header 

Logo & some small sentence about our goal and how **OPEN** we are 

—————

What does Open Source Community mean ? 
...
...
...

—————-

About this community and what’s our goal 

...
...

### Projects :
![image](https://user-images.githubusercontent.com/16967174/79141761-f31e0f80-7da9-11ea-8fce-42a17c47efa5.png)

—————-
*Transition between our goal and what we are doing and how to contribute* 
= how to join the community, join us on social networks.....

——————-

Made with ❤️ by Algerians to Algerians or something like this ( by Algerians for Algeria .... )

**Comment by SofianeHamlaoui** [comment]
- A dark mode switch 

![image](https://user-images.githubusercontent.com/16967174/79195704-03c49900-7e2f-11ea-89f2-db4e01cac2c7.jpeg)

**Comment by SofianeHamlaoui** [comment]
- subscribing to Newsletter for Open Source news

**Comment by SofianeHamlaoui** [comment]
## Simple Prototyping 1 : 
![image](https://user-images.githubusercontent.com/16967174/79447792-eaa71e00-7fcf-11ea-8f78-12aba152f57f.png)

## Simple Prototyping 2 : 
![image](https://user-images.githubusercontent.com/16967174/79447849-06122900-7fd0-11ea-836b-e8ef1390a069.png)

## Colors : 

### 1 ( cc @SofianeHamlaoui :+1: ) : 
![image](https://user-images.githubusercontent.com/16967174/79447894-14f8db80-7fd0-11ea-9d05-aa105a2a406f.png)
### 2 ( cc @SofianeHamlaoui :+1: ) :
![image](https://user-images.githubusercontent.com/16967174/79448295-b54f0000-7fd0-11ea-943e-f5542e2437b9.png)
### 3 ( cc @SofianeHamlaoui :+1: )  : 
![image](https://user-images.githubusercontent.com/16967174/79448318-bed86800-7fd0-11ea-8179-314a9c92aad8.png)
### 4 : 
![image](https://user-images.githubusercontent.com/16967174/79448406-e7f8f880-7fd0-11ea-89af-8014d0ce8eca.png)
### 5 ( cc @SofianeHamlaoui :1st_place_medal: : ): 
![image](https://user-images.githubusercontent.com/16967174/79448509-0fe85c00-7fd1-11ea-8147-9f8996a5971f.png)
### 6 : 
![image](https://user-images.githubusercontent.com/16967174/79448616-3efecd80-7fd1-11ea-8ced-28f2ad5aebf9.png)
### 7 ( cc @SofianeHamlaoui :1st_place_medal: ) : 
![image](https://user-images.githubusercontent.com/16967174/79448673-5b9b0580-7fd1-11ea-99a7-a326f62b5aa8.png)

**Comment by SofianeHamlaoui** [comment]
### 1 ( cc @SofianeHamlaoui :+1: ) : 
![image](https://user-images.githubusercontent.com/16967174/79447894-14f8db80-7fd0-11ea-9d05-aa105a2a406f.png)

**Comment by SofianeHamlaoui** [comment]
### 2 ( cc @SofianeHamlaoui :+1: ) :
![image](https://user-images.githubusercontent.com/16967174/79448295-b54f0000-7fd0-11ea-943e-f5542e2437b9.png)

**Comment by SofianeHamlaoui** [comment]
### 3 ( cc @SofianeHamlaoui :+1: )  : 
![image](https://user-images.githubusercontent.com/16967174/79448318-bed86800-7fd0-11ea-8179-314a9c92aad8.png)

**Comment by SofianeHamlaoui** [comment]
### 4 : 
![image](https://user-images.githubusercontent.com/16967174/79448406-e7f8f880-7fd0-11ea-89af-8014d0ce8eca.png)

**Comment by SofianeHamlaoui** [comment]
### 5 ( cc @SofianeHamlaoui :1st_place_medal: : ): 
![image](https://user-images.githubusercontent.com/16967174/79448509-0fe85c00-7fd1-11ea-8147-9f8996a5971f.png)

**Comment by SofianeHamlaoui** [comment]
### 6 : 
![image](https://user-images.githubusercontent.com/16967174/79448616-3efecd80-7fd1-11ea-8ced-28f2ad5aebf9.png)

**Comment by SofianeHamlaoui** [comment]
### 7 ( cc @SofianeHamlaoui :1st_place_medal: ) : 
![image](https://user-images.githubusercontent.com/16967174/79448673-5b9b0580-7fd1-11ea-99a7-a326f62b5aa8.png)
