### ISSUE TITLE
Switching languages does not work properly

### ISSUE THREAD

**Issue by omdxp** [dzcode-io/dzcode.io#625]
**Describe the bug**
When I switch language from English to Arabic and then switching back it keeps using Arabic.

**To Reproduce**

1. Go to [dzcode.io](https://www.dzcode.io)
2. Click on language button `English`
3. Scroll down to `Arabic`
4. Click on it and the website will be refreshed with Arabic
5. Click on language button `Arabic`
6. Click on `English`
7. Website is refreshed but it keeps using Arabic language (even after clicking many times)

**Expected behavior**
Switching languages should be seamless without any problems.

**Environment:**

- OS: MacOS
- Browser : Safari / Chrome

**Comment by ZibanPirate** [comment]
This is only reproducible on the root `/`, the rest of the pages work fine it seems

**Comment by omdxp** [comment]
I'll have a look on it today
