### ISSUE TITLE
Article Suggestion 

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#75]

**Comment by NurElHuda** [comment]
Hello, 

I am working on a draft on Open Source Software. 

At first, I intended it to be on "How to contribute to open-source software?". However, it got bigger and bigger where it included "What is open source?" and "why we should contribute to open source?" 

I am now puzzled between splitting it into 3 different articles with 500 words each or leaving it as a one long through article.

What do you guys think?

**Comment by ZibanPirate** [comment]
@NurElHuda content size doesn't maters as much as publishing it, always remembers you and we can change it for the better later on

**Comment by Souhaib-Benbouzid** [comment]
> @NurElHuda content size doesn't maters as much as publishing it, always remembers you and we can change it for the better later on
 
thank you @ZibanPirate for the clarification. @NurElHuda I will be closing this issue since you added your article.
