### ISSUE TITLE
ESLint pattern can't detect any files on windows

### ISSUE THREAD

**Issue by Souhaib-Benbouzid** [dzcode-io/dzcode.io#86]
**Describe the bug**

ESLint pattern can't detect any files on windows when trying to commit 

**To Reproduce**
1. Go to 'frontend'
2. edit and stage and any file
3. Commit changes
```
$ git commit -m "test"
husky > pre-commit (node v12.18.1)
$ eslint '*{,/**/*}.{js,ts,tsx}' --report-unused-disable-directives

Oops! Something went wrong! :(

ESLint: 6.8.0.

No files matching the pattern "'*{,/**/*}.{js,ts,tsx}'" were found.
Please check for typing mistakes in the pattern.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky > pre-commit hook failed (add --no-verify to bypass)

```

**Expected behavior**
commit new changes

**Screenshots**

![Capture](https://user-images.githubusercontent.com/54677068/88050699-42b16b80-cb4f-11ea-955b-0dcaa1096dd7.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ZibanPirate** [comment]
Thanks for reporting @Souhaib-Benbouzid , it's now fixed, see #87
